### ISSUE TITLE
SCAMMMMMMM

### ISSUE THREAD

**Issue by valorant852456** [wh-Cyberspace/Wh-Rat-V2#4]

**Comment by wh-Cyberspace** [comment]
[+] Uninstall app > ( New )_____________________ [+] self Uninstall > ( New )

[+] Send Sms > ( New ) __________________________[+] Device administrator mode > ( New )

**Comment by wh-Cyberspace** [comment]
[+] Uninstall app > ( New )_____________________ [+] self Uninstall > ( New )

[+] Send Sms > ( New ) __________________________[+] Device administrator mode > ( New )
