### ISSUE TITLE
Useless Tool Ever Seen Before !

### ISSUE THREAD

**Issue by purplepheonixp8p** [wh-Cyberspace/Wh-Rat-V2#5]

**Comment by wh-Cyberspace** [comment]
[+] Uninstall app > ( New )_____________________ [+] self Uninstall > ( New )

[+] Send Sms > ( New ) __________________________[+] Device administrator mode > ( New )

**Comment by wh-Cyberspace** [comment]
[+] Uninstall app > ( New )_____________________ [+] self Uninstall > ( New )

[+] Send Sms > ( New ) __________________________[+] Device administrator mode > ( New )
